{{- if .Values.autoUpdate.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ include "zesty-k8s.fullname" . }}-updater"
  labels:
    app.kubernetes.io/instance: "{{ include "zesty-k8s.fullname" . }}"
    app.kubernetes.io/name: "{{ include "zesty-k8s.fullname" . }}"
    date: "{{ now | unixEpoch }}"
spec:
  schedule: "{{ .Values.autoUpdate.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            kubernetes.io/arch: amd64
          containers:
            - name: zesty-k8s-updater
              image: "{{ .Values.image.repository }}:{{ include "zesty-k8s.version" . }}" 
              imagePullPolicy: Always
              env:
              - name: RELEASE_NAME
                value: "{{ .Release.Name }}"
              - name: NAMESPACE
                value: "{{ include "zesty-k8s.namespace" . }}"
          restartPolicy: Never
      backoffLimit: 4
{{- end }}