apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "zesty-k8s.secret" . }}"
  labels:
    app.kubernetes.io/instance: "{{ include "zesty-k8s.fullname" . }}"
    app.kubernetes.io/name: "{{ include "zesty-k8s.fullname" . }}"
