{{- if .Values.autoUpdate.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "zesty-k8s.autoupdate-saname" . }}"
  labels:
    app.kubernetes.io/instance: "{{ include "zesty-k8s.fullname" . }}"
    app.kubernetes.io/name: "{{ include "zesty-k8s.fullname" . }}"
{{- if .Values.serviceAccount.annotations }}
  annotations:
{{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end -}}
{{- end }}